// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9pTqMdH0w6fVDHDJpRlnijcFnVn4NU9s',
    appId: '1:779782112695:web:c8254c35af5ad0820c9432',
    messagingSenderId: '779782112695',
    projectId: 'todo-565a9',
    authDomain: 'todo-565a9.firebaseapp.com',
    storageBucket: 'todo-565a9.firebasestorage.app',
    measurementId: 'G-6QFDZVHDJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLkU-wwXCKjBug7ASiyyxFikL2tZmo-yA',
    appId: '1:779782112695:android:e5e97ece75107c8d0c9432',
    messagingSenderId: '779782112695',
    projectId: 'todo-565a9',
    storageBucket: 'todo-565a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0XEOJMwW_KvvNaBSswm4-mzcmb9pRXQ',
    appId: '1:779782112695:ios:6ad0ce1a5b425b970c9432',
    messagingSenderId: '779782112695',
    projectId: 'todo-565a9',
    storageBucket: 'todo-565a9.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH0XEOJMwW_KvvNaBSswm4-mzcmb9pRXQ',
    appId: '1:779782112695:ios:6ad0ce1a5b425b970c9432',
    messagingSenderId: '779782112695',
    projectId: 'todo-565a9',
    storageBucket: 'todo-565a9.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9pTqMdH0w6fVDHDJpRlnijcFnVn4NU9s',
    appId: '1:779782112695:web:871ed72d1ae6bc850c9432',
    messagingSenderId: '779782112695',
    projectId: 'todo-565a9',
    authDomain: 'todo-565a9.firebaseapp.com',
    storageBucket: 'todo-565a9.firebasestorage.app',
    measurementId: 'G-Y0B9FNYGKX',
  );
}
